stations:
- id: '1'
  name: Station_1
  city: Station_1
  short_name: Station_1
  coordinates:
    latitude: 40.406442
    longitude: -3.690886
- id: '2'
  name: Station_2
  city: Station_2
  short_name: Station_2
  coordinates:
    latitude: 40.406442
    longitude: -3.690886
- id: '3'
  name: Station_3
  city: Station_3
  short_name: Station_3
  coordinates:
    latitude: 40.406442
    longitude: -3.690886
- id: '4'
  name: Station_4
  city: Station_4
  short_name: Station_4
  coordinates:
    latitude: 40.406442
    longitude: -3.690886

seat:
- id: '1'
  name: Basic
  hard_type: 1
  soft_type: 1
- id: '2'
  name: Premium
  hard_type: 2
  soft_type: 1

corridor:
- id: '1'
  name: Station_1 - Station_4
  stations:
  - org: '1'
    des:
    - org: '2'
      des:
      - org: '3'
        des:
        - org: '4'
          des: []
    - org: '3'
      des:
      - org: '4'
        des: []
    - org: '4'
      des: []

line:
- id: '1'
  name: Line 1 - 2
  corridor: '1'
  stops:
  - station: '1'
    arrival_time: 0
    departure_time: 0
  - station: '2'
    arrival_time: 30
    departure_time: 30
- id: '2'
  name: Line 1 - 2 - 3
  corridor: '1'
  stops:
  - station: '1'
    arrival_time: 0
    departure_time: 0
  - station: '2'
    arrival_time: 30
    departure_time: 35
  - station: '3'
    arrival_time: 50
    departure_time: 50
- id: '3'
  name: Line 1 - 2 - 3 - 4
  corridor: '1'
  stops:
  - station: '1'
    arrival_time: 0
    departure_time: 0
  - station: '2'
    arrival_time: 30
    departure_time: 35
  - station: '3'
    arrival_time: 50
    departure_time: 55
  - station: '4'
    arrival_time: 55
    departure_time: 85
- id: '4'
  name: Line 1 - 3
  corridor: '1'
  stops:
  - station: '1'
    arrival_time: 0
    departure_time: 0
  - station: '3'
    arrival_time: 35
    departure_time: 35
- id: '5'
  name: Line 1 - 3 - 4
  corridor: '1'
  stops:
  - station: '1'
    arrival_time: 0
    departure_time: 0
  - station: '3'
    arrival_time: 35
    departure_time: 40
  - station: '4'
    arrival_time: 70
    departure_time: 70
- id: '6'
  name: Line 1 - 4
  corridor: '1'
  stops:
  - station: '1'
    arrival_time: 0
    departure_time: 0
  - station: '4'
    arrival_time: 45
    departure_time: 45

rollingStock:
- id: 1
  name: S-114
  seats:
  - hard_type: 1
    quantity: 250
  - hard_type: 2
    quantity: 50

trainServiceProvider:
- id: '1'
  name: Renfe
  rolling_stock:
  - '1'
- id: '2'
  name: Ouigo
  rolling_stock:
  - '1'
- id: '3'
  name: Iryo
  rolling_stock:
  - '1'

timeSlot:
- id: '45010'
  start: '7:30:00'
  end: '7:40:00'
- id: '108010'
  start: '18:00:00'
  end: '18:10:00'
- id: '51010'
  start: '8:30:00'
  end: '8:40:00'
- id: '57010'
  start: '9:30:00'
  end: '9:40:00'
- id: '99010'
  start: '16:30:00'
  end: '16:40:00'
- id: '117010'
  start: '19:30:00'
  end: '19:40:00'
- id: '48010'
  start: '8:00:00'
  end: '8:10:00'
- id: '54010'
  start: '9:00:00'
  end: '9:10:00'
- id: '124010'
  start: '20:40:00'
  end: '20:50:00'
- id: '42010'
  start: '7:00:00'
  end: '7:10:00'
- id: '111010'
  start: '18:30:00'
  end: '18:40:00'
- id: '39010'
  start: '6:30:00'
  end: '6:40:00'
- id: '87010'
  start: '14:30:00'
  end: '14:40:00'
- id: '37510'
  start: '6:15:00'
  end: '6:25:00'
- id: '75010'
  start: '12:30:00'
  end: '12:40:00'
- id: '93010'
  start: '15:30:00'
  end: '15:40:00'
- id: '114010'
  start: '19:00:00'
  end: '19:10:00'
- id: '127010'
  start: '21:10:00'
  end: '21:20:00'
- id: '78010'
  start: '13:00:00'
  end: '13:10:00'
- id: '105010'
  start: '17:30:00'
  end: '17:40:00'
- id: '63010'
  start: '10:30:00'
  end: '10:40:00'
- id: '102010'
  start: '17:00:00'
  end: '17:10:00'
- id: '69010'
  start: '11:30:00'
  end: '11:40:00'
- id: '96010'
  start: '16:00:00'
  end: '16:10:00'
- id: '90010'
  start: '15:00:00'
  end: '15:10:00'

service:
# This service is from last year to test actions that are irrelevant
- id: 5_06-09-2022-06.15
  date: '2022-09-06'
  line: '5'
  train_service_provider: '1'
  time_slot: '37510'
  rolling_stock: '1'
  origin_destination_tuples:
  - origin: '1'
    destination: '4'
    seats:
    - seat: '1'
      price: 50.0
    - seat: '2'
      price: 75.0
  capacity_constraints: null
- id: 5_06-09-2023-06.15
  date: '2023-09-06'
  line: '5'
  train_service_provider: '1'
  time_slot: '37510'
  rolling_stock: '1'
  origin_destination_tuples:
  - origin: '1'
    destination: '4'
    seats:
    - seat: '1'
      price: 70.0
    - seat: '2'
      price: 115.0
  capacity_constraints: null
- id: 6_06-09-2023-06.15
  date: '2023-09-06'
  line: '6'
  train_service_provider: '1'
  time_slot: '37510'
  rolling_stock: '1'
  origin_destination_tuples:
  - origin: '1'
    destination: '4'
    seats:
    - seat: '1'
      price: 100.0
    - seat: '2'
      price: 150.0
  capacity_constraints: null
- id: 5_06-09-2023-18.30
  date: '2023-09-06'
  line: '5'
  train_service_provider: '1'
  time_slot: '111010'
  rolling_stock: '1'
  origin_destination_tuples:
  - origin: '1'
    destination: '4'
    seats:
    - seat: '1'
      price: 70.0
    - seat: '2'
      price: 115.0
  capacity_constraints: null
- id: 6_06-09-2023-18.30
  date: '2023-09-06'
  line: '6'
  train_service_provider: '1'
  time_slot: '111010'
  rolling_stock: '1'
  origin_destination_tuples:
  - origin: '1'
    destination: '4'
    seats:
    - seat: '1'
      price: 100.0
    - seat: '2'
      price: 150.0
  capacity_constraints: null
# This service is from last year to test actions that are irrelevant
- id: 5_06-09-2022-06.15_b
  date: '2022-09-06'
  line: '5'
  train_service_provider: '2'
  time_slot: '37510'
  rolling_stock: '1'
  origin_destination_tuples:
  - origin: '1'
    destination: '4'
    seats:
    - seat: '1'
      price: 50.0
    - seat: '2'
      price: 75.0
  capacity_constraints: null
- id: 5_06-09-2023-06.15_b
  date: '2023-09-06'
  line: '5'
  train_service_provider: '2'
  time_slot: '37510'
  rolling_stock: '1'
  origin_destination_tuples:
  - origin: '1'
    destination: '4'
    seats:
    - seat: '1'
      price: 70.0
    - seat: '2'
      price: 115.0
  capacity_constraints: null
- id: 6_06-09-2023-06.15_b
  date: '2023-09-06'
  line: '6'
  train_service_provider: '2'
  time_slot: '37510'
  rolling_stock: '1'
  origin_destination_tuples:
  - origin: '1'
    destination: '4'
    seats:
    - seat: '1'
      price: 100.0
    - seat: '2'
      price: 150.0
  capacity_constraints: null
- id: 5_06-09-2023-18.30_b
  date: '2023-09-06'
  line: '5'
  train_service_provider: '2'
  time_slot: '111010'
  rolling_stock: '1'
  origin_destination_tuples:
  - origin: '1'
    destination: '4'
    seats:
    - seat: '1'
      price: 70.0
    - seat: '2'
      price: 115.0
  capacity_constraints: null
- id: 6_06-09-2023-18.30_b
  date: '2023-09-06'
  line: '6'
  train_service_provider: '2'
  time_slot: '111010'
  rolling_stock: '1'
  origin_destination_tuples:
  - origin: '1'
    destination: '4'
    seats:
    - seat: '1'
      price: 100.0
    - seat: '2'
      price: 150.0
  capacity_constraints: null
# This service is from last year to test actions that are irrelevant
- id: 5_06-09-2022-06.15_c
  date: '2022-09-06'
  line: '5'
  train_service_provider: '3'
  time_slot: '37510'
  rolling_stock: '1'
  origin_destination_tuples:
  - origin: '1'
    destination: '4'
    seats:
    - seat: '1'
      price: 50.0
    - seat: '2'
      price: 75.0
  capacity_constraints: null
- id: 5_06-09-2023-06.15_c
  date: '2023-09-06'
  line: '5'
  train_service_provider: '3'
  time_slot: '37510'
  rolling_stock: '1'
  origin_destination_tuples:
  - origin: '1'
    destination: '4'
    seats:
    - seat: '1'
      price: 70.0
    - seat: '2'
      price: 115.0
  capacity_constraints: null
- id: 6_06-09-2023-06.15_c
  date: '2023-09-06'
  line: '6'
  train_service_provider: '3'
  time_slot: '37510'
  rolling_stock: '1'
  origin_destination_tuples:
  - origin: '1'
    destination: '4'
    seats:
    - seat: '1'
      price: 100.0
    - seat: '2'
      price: 150.0
  capacity_constraints: null
- id: 5_06-09-2023-18.30_c
  date: '2023-09-06'
  line: '5'
  train_service_provider: '3'
  time_slot: '111010'
  rolling_stock: '1'
  origin_destination_tuples:
  - origin: '1'
    destination: '4'
    seats:
    - seat: '1'
      price: 70.0
    - seat: '2'
      price: 115.0
  capacity_constraints: null
- id: 6_06-09-2023-18.30_c
  date: '2023-09-06'
  line: '6'
  train_service_provider: '3'
  time_slot: '111010'
  rolling_stock: '1'
  origin_destination_tuples:
  - origin: '1'
    destination: '4'
    seats:
    - seat: '1'
      price: 100.0
    - seat: '2'
      price: 150.0
  capacity_constraints: null
