stations:
- id: 'A'
  name: Station_A
  city: Station_A
  short_name: Station_A
  coordinates:
    latitude: 40.406442
    longitude: -3.690886
- id: 'B'
  name: Station_B
  city: Station_B
  short_name: Station_B
  coordinates:
    latitude: 40.406442
    longitude: -3.690886
- id: 'C'
  name: Station_C
  city: Station_C
  short_name: Station_C
  coordinates:
    latitude: 40.406442
    longitude: -3.690886
- id: 'D'
  name: Station_D
  city: Station_D
  short_name: Station_D
  coordinates:
    latitude: 40.406442
    longitude: -3.690886

seat:
- id: '1'
  name: Basic
  hard_type: 1
  soft_type: 1
- id: '2'
  name: Premium
  hard_type: 2
  soft_type: 1

corridor:
- id: '1'
  name: Station_1 - Station_4
  stations:
  - org: 'A'
    des:
    - org: 'B'
      des:
      - org: 'C'
        des: []
    - org: 'C'
      des: []
    - org: 'D'
      des: []

line:
- id: '1'
  name: Line A - C
  corridor: '1'
  stops:
  - station: 'A'
    arrival_time: 0
    departure_time: 0
  - station: 'C'
    arrival_time: 60
    departure_time: 60
- id: '2'
  name: Line A - B
  corridor: '1'
  stops:
  - station: 'A'
    arrival_time: 0
    departure_time: 0
  - station: 'B'
    arrival_time: 45
    departure_time: 45
- id: '3'
  name: Line B - C
  corridor: '1'
  stops:
  - station: 'B'
    arrival_time: 0
    departure_time: 0
  - station: 'C'
    arrival_time: 30
    departure_time: 30
- id: '4'
  name: Line A - D
  corridor: '1'
  stops:
  - station: 'A'
    arrival_time: 0
    departure_time: 25
  - station: 'D'
    arrival_time: 25
    departure_time: 25

rollingStock:
- id: 1
  name: S-114
  seats:
  - hard_type: 1
    quantity: 250
  - hard_type: 2
    quantity: 50

trainServiceProvider:
- id: '1'
  name: Renfe
  rolling_stock:
  - '1'
- id: '2'
  name: Ouigo
  rolling_stock:
  - '1'
- id: '3'
  name: Iryo
  rolling_stock:
  - '1'

timeSlot:
- id: '1'
  start: '8:00:00'
  end: '8:10:00'
- id: '2'
  start: '9:00:00'
  end: '9:10:00'

service:
- id: 1_06-09-2023-08.00
  date: '2023-09-06'
  line: '1'
  train_service_provider: '1'
  time_slot: '1'
  rolling_stock: '1'
  origin_destination_tuples:
  - origin: 'A'
    destination: 'C'
    seats:
    - seat: '1'
      price: 50.0
  capacity_constraints: null
- id: 2_06-09-2023-08.00
  date: '2023-09-06'
  line: '2'
  train_service_provider: '2'
  time_slot: '1'
  rolling_stock: '1'
  origin_destination_tuples:
  - origin: 'A'
    destination: 'B'
    seats:
    - seat: '1'
      price: 25.0
  capacity_constraints: null
- id: 3_06-09-2023-09:00
  date: '2023-09-06'
  line: '3'
  train_service_provider: '3'
  time_slot: '2'
  rolling_stock: '1'
  origin_destination_tuples:
  - origin: 'B'
    destination: 'C'
    seats:
    - seat: '1'
      price: 20.0
  capacity_constraints: null
- id: 4_06-09-2023-08.00
  date: '2023-09-06'
  line: '4'
  train_service_provider: '2'
  time_slot: '1'
  rolling_stock: '1'
  origin_destination_tuples:
  - origin: 'A'
    destination: 'D'
    seats:
    - seat: '1'
      price: 50.0
  capacity_constraints: null
- id: 4_06-09-2023-08.00b
  date: '2023-09-06'
  line: '4'
  train_service_provider: '3'
  time_slot: '1'
  rolling_stock: '1'
  origin_destination_tuples:
  - origin: 'A'
    destination: 'D'
    seats:
    - seat: '1'
      price: 50.0
  capacity_constraints: null
